version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:latest
    
    steps:
      - run: echo hello


workflows:
  version: 2
  dev_stage_pre-prod:
    jobs:
      - test:
          filters:
            branches:
              only: dev-*
